import Head from 'next/head'
import Header from '../components/Header/Header';
import styles from '../styles/Home.module.scss'
import Greetings from '../components/Greetings/Greetings';
import Services from '../components/Services/Services';
import React, {useState} from 'react';
import Partners from '../components/Partners/Partners';
import Image from 'next/image';
import back from '../assets/background.svg'
import ModalWrapper from '../components/Modal/ModalWrapper';

export default function Home() {
    const [isModalOpen, setIsModalOpen] = useState(false);
    const showModal = () => {
        setIsModalOpen(true);
    };
    const handleOk = () => {
        setIsModalOpen(false);
    };
    const handleCancel = () => {
        setIsModalOpen(false);
    };

    const container = isModalOpen ? `${styles.main} ${styles.disabled}` : styles.main

    return (
        <>
            <Head>
                <title>LandVille</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <div className={container}>
                <Image src={back} alt={`background`} className={styles.background}/>
                <Header showModal={showModal}/>
                <Greetings/>
                <Services/>
                <Partners showModal={showModal}/>
                {isModalOpen && <ModalWrapper closeModal={handleCancel} title={'Contact Us'}/>}
            </div>
        </>
    )
}
